#!/usr/bin/env python3
"""Translate ALL remaining English glosses to Russian in PODSTR JSON files.

Uses a comprehensive word-level dictionary plus phrase-level patterns.
"""
import json
import glob
import os
import re

WORD_MAP = {
    # Articles/particles (empty = skip)
    "the": "", "a": "", "an": "", "The": "", "A": "", "An": "",
    "<the>": "", "<a>": "", "<an>": "", "<to>": "",
    "[доп.]": "", "[add]": "",
    
    # Conjunctions & prepositions
    "and": "и", "or": "или", "but": "но", "yet": "однако",
    "not": "не", "no": "нет", "nor": "ни",
    "if": "если", "then": "тогда", "than": "чем",
    "that": "что", "which": "который", "who": "кто", "whom": "кому",
    "whose": "чей", "what": "что", "when": "когда", "where": "где",
    "how": "как", "why": "почему", "whether": "ли",
    "to": "к", "for": "для", "from": "от", "with": "с", "by": "через",
    "in": "в", "into": "в", "on": "на", "at": "у", "upon": "на",
    "over": "над", "under": "под", "before": "перед", "after": "после",
    "until": "до", "between": "между", "among": "среди",
    "against": "против", "about": "о", "through": "через",
    "of": "", "out": "из", "up": "вверх", "down": "вниз",
    "off": "прочь", "away": "прочь", "back": "назад",
    "along": "вдоль", "across": "через", "around": "вокруг",
    "behind": "позади", "beside": "рядом", "beyond": "за",
    "within": "внутри", "without": "без", "toward": "к", "towards": "к",
    "during": "во время", "since": "с тех пор", "except": "кроме",
    "instead": "вместо", "despite": "несмотря на",
    "concerning": "относительно", "according": "согласно",
    "near": "вблизи", "far": "далеко", "above": "над", "below": "под",
    "inside": "внутри", "outside": "снаружи",
    "also": "также", "even": "даже", "only": "только",
    "now": "ныне", "here": "здесь", "there": "там",
    "thus": "так", "so": "так", "therefore": "поэтому",
    "however": "однако", "nevertheless": "тем не менее",
    "moreover": "более того", "furthermore": "кроме того",
    "indeed": "воистину", "truly": "истинно", "surely": "верно",
    "perhaps": "может быть", "maybe": "может быть",
    "rather": "скорее", "neither": "ни", "either": "либо",
    "both": "оба", "too": "тоже", "well": "хорошо",
    "still": "ещё", "already": "уже", "again": "снова",
    "ever": "когда-либо", "never": "никогда", "always": "всегда",
    "forever": "вовек", "today": "сегодня", "tomorrow": "завтра",
    "yesterday": "вчера", "soon": "скоро", "later": "позже",
    "then": "тогда", "just": "только", "merely": "лишь",
    "almost": "почти", "quite": "вполне", "entirely": "полностью",
    "certainly": "непременно", "definitely": "определённо",
    "immediately": "тотчас", "suddenly": "внезапно",
    "continually": "непрестанно", "constantly": "постоянно",
    "exceedingly": "чрезвычайно", "greatly": "весьма",
    "especially": "особенно", "meanwhile": "тем временем",
    "anyway": "всё равно", "otherwise": "иначе",
    "hence": "отсюда", "thence": "оттуда", "whence": "откуда",
    "hither": "сюда", "thither": "туда",
    "forth": "вперёд", "forward": "вперёд",
    "abroad": "далеко", "apart": "отдельно",
    "alone": "один", "together": "вместе",
    "thereof": "того", "wherein": "в чём",
    "wherefore": "потому", "whereas": "тогда как",
    "unto": "к", "lest": "чтобы не", "unless": "если не",
    "whilst": "пока",

    # Pronouns
    "I": "я", "me": "меня", "my": "мой", "mine": "мой",
    "myself": "сам", "we": "мы", "us": "нас", "our": "наш",
    "ourselves": "сами",
    "you": "ты", "your": "твой", "yours": "твой",
    "yourself": "себя", "yourselves": "сами",
    "he": "он", "him": "его", "his": "его", "himself": "сам",
    "she": "она", "her": "её", "herself": "сама",
    "it": "оно", "its": "его", "itself": "само",
    "they": "они", "them": "их", "their": "их",
    "themselves": "сами",
    "this": "это", "that": "тот", "these": "эти", "those": "те",
    "one": "один", "ones": "те", "other": "другой", "others": "другие",
    "another": "другой", "same": "тот же", "own": "свой",
    "self": "сам", "such": "такой", "some": "некоторые",
    "any": "любой", "each": "каждый", "every": "каждый",
    "all": "все", "whole": "весь", "entire": "весь",
    "many": "многие", "much": "много", "more": "более",
    "most": "наиболее", "few": "немногие", "less": "менее",
    "least": "наименьший", "several": "несколько",
    "certain": "некий", "whoever": "кто бы ни",
    "whatever": "что бы ни", "anyone": "кто-либо",
    "everyone": "каждый", "someone": "кто-то",
    "anything": "что-либо", "everything": "всё",
    "something": "нечто", "nothing": "ничто",
    "nobody": "никто", "none": "никто",

    # Numbers
    "two": "два", "three": "три", "four": "четыре",
    "five": "пять", "six": "шесть", "seven": "семь",
    "eight": "восемь", "nine": "девять", "ten": "десять",
    "eleven": "одиннадцать", "twelve": "двенадцать",
    "thirteen": "тринадцать", "fourteen": "четырнадцать",
    "fifteen": "пятнадцать", "sixteen": "шестнадцать",
    "seventeen": "семнадцать", "eighteen": "восемнадцать",
    "nineteen": "девятнадцать", "twenty": "двадцать",
    "thirty": "тридцать", "forty": "сорок", "fifty": "пятьдесят",
    "sixty": "шестьдесят", "seventy": "семьдесят",
    "eighty": "восемьдесят", "ninety": "девяносто",
    "hundred": "сто", "thousand": "тысяча", "million": "миллион",
    "first": "первый", "second": "второй", "third": "третий",
    "fourth": "четвёртый", "fifth": "пятый", "sixth": "шестой",
    "seventh": "седьмой", "eighth": "восьмой", "ninth": "девятый",
    "tenth": "десятый", "hundredth": "сотый",
    "half": "половина", "third": "треть", "quarter": "четверть",
    "double": "двойной", "triple": "тройной",
    "teen": "надцать", "plus": "плюс",

    # Verbs - be/have/do
    "be": "быть", "is": "есть", "am": "есмь", "are": "суть",
    "was": "был", "were": "были", "been": "был",
    "being": "будучи", "become": "стать", "became": "стал",
    "becomes": "становится",
    "has": "имеет", "have": "имеют", "had": "имел",
    "having": "имея",
    "do": "делать", "does": "делает", "did": "сделал",
    "done": "сделано", "doing": "делая",

    # Verbs - movement
    "go": "идти", "goes": "идёт", "went": "пошёл",
    "gone": "ушёл", "going": "идя",
    "come": "прийти", "comes": "приходит", "came": "пришёл",
    "coming": "приходящий",
    "walk": "ходить", "walked": "ходил", "walking": "ходя",
    "walks": "ходит",
    "run": "бежать", "ran": "побежал", "running": "бегущий",
    "flee": "бежать", "fled": "бежал", "fleeing": "бегущий",
    "return": "возвратиться", "returned": "возвратился",
    "returning": "возвращаясь", "returns": "возвращается",
    "enter": "войти", "entered": "вошёл", "entering": "входящий",
    "leave": "оставить", "left": "оставил", "leaving": "покидая",
    "depart": "уйти", "departed": "ушёл",
    "pass": "пройти", "passed": "прошёл", "passing": "проходя",
    "cross": "перейти", "crossed": "перешёл", "crossing": "переходя",
    "follow": "следовать", "followed": "последовал",
    "following": "следуя",
    "lead": "вести", "led": "вёл", "leading": "ведущий",
    "pursue": "преследовать", "pursued": "преследовал",
    "send": "послать", "sent": "послал", "sending": "посылая",
    "bring": "принести", "brought": "принёс", "bringing": "принося",
    "carry": "нести", "carried": "нёс", "carrying": "неся",
    "take": "взять", "took": "взял", "taken": "взятый",
    "taking": "беря",
    "draw": "тянуть", "drew": "вытянул", "drawn": "вытянутый",
    "turn": "повернуть", "turned": "повернулся",
    "turning": "поворачивая",
    "rise": "встать", "rose": "встал", "risen": "воскресший",
    "rising": "восставая",
    "arise": "восстать", "arose": "восстал",
    "fall": "упасть", "fell": "упал", "fallen": "падший",
    "falling": "падая",
    "sit": "сидеть", "sat": "сидел", "sitting": "сидя",
    "stand": "стоять", "stood": "стоял", "standing": "стоя",
    "lie": "лежать", "lay": "лёг", "lying": "лежащий",
    "remain": "оставаться", "remained": "оставался",
    "remaining": "остающийся",
    "stay": "оставаться", "stayed": "оставался",
    "dwell": "обитать", "dwelt": "обитал", "dwelling": "обитающий",
    "ascend": "восходить", "ascended": "взошёл",
    "ascending": "восходящий",
    "descend": "нисходить", "descended": "сошёл",
    "descending": "нисходящий",
    "climb": "подниматься", "climbed": "поднялся",
    "jump": "прыгать", "jumped": "прыгнул",

    # Verbs - speech
    "say": "сказать", "says": "говорит", "said": "сказал",
    "saying": "говоря",
    "speak": "говорить", "spoke": "говорил", "spoken": "сказанное",
    "speaking": "говоря",
    "tell": "сказать", "told": "сказал", "telling": "говоря",
    "call": "звать", "called": "назвал", "calling": "зовя",
    "cry": "вопиять", "cried": "воззвал", "crying": "вопия",
    "shout": "кричать", "shouted": "закричал",
    "answer": "ответить", "answered": "ответил",
    "answering": "отвечая",
    "ask": "спросить", "asked": "спросил", "asking": "спрашивая",
    "pray": "молиться", "prayed": "молился", "praying": "молясь",
    "praise": "хвалить", "praised": "восхвалил",
    "praising": "хваля",
    "sing": "петь", "sang": "пел", "sung": "воспетый",
    "singing": "поя",
    "declare": "объявить", "declared": "объявил",
    "proclaim": "провозгласить", "proclaimed": "провозгласил",
    "testify": "свидетельствовать", "testified": "засвидетельствовал",
    "confess": "исповедовать", "confessed": "исповедал",
    "swear": "клясться", "swore": "клялся", "sworn": "клятый",
    "promise": "обещать", "promised": "обещал",
    "threaten": "угрожать", "threatened": "угрожал",
    "command": "повелеть", "commanded": "повелел",
    "commanding": "повелевая",
    "order": "повелеть", "ordered": "повелел",
    "summon": "призвать", "summoned": "призвал",
    "invite": "пригласить", "invited": "пригласил",
    "warn": "предупредить", "warned": "предупредил",
    "rebuke": "упрекать", "rebuked": "упрекнул",
    "accuse": "обвинять", "accused": "обвинял",
    "deny": "отрицать", "denied": "отрёкся",
    "listen": "слушать", "listened": "слушал", "listening": "слушая",
    "whisper": "шептать", "whispered": "шептал",

    # Verbs - cognition/perception
    "see": "видеть", "saw": "увидел", "seen": "виденный",
    "seeing": "видя",
    "look": "смотреть", "looked": "посмотрел", "looking": "смотря",
    "watch": "наблюдать", "watched": "наблюдал",
    "behold": "вот", "beheld": "увидел",
    "hear": "слышать", "heard": "услышал", "hearing": "слыша",
    "know": "знать", "knew": "знал", "known": "известный",
    "knowing": "зная",
    "think": "думать", "thought": "подумал", "thinking": "думая",
    "understand": "понимать", "understood": "понял",
    "understanding": "понимание",
    "believe": "верить", "believed": "поверил",
    "remember": "помнить", "remembered": "вспомнил",
    "forget": "забыть", "forgot": "забыл", "forgotten": "забытый",
    "recognize": "узнать", "recognized": "узнал",
    "perceive": "воспринимать", "perceived": "воспринял",
    "consider": "рассмотреть", "considered": "рассмотрел",
    "suppose": "полагать", "supposed": "полагал",
    "realize": "осознать", "realized": "осознал",
    "discover": "обнаружить", "discovered": "обнаружил",
    "notice": "заметить", "noticed": "заметил",

    # Verbs - action
    "make": "делать", "made": "сделал", "making": "делая",
    "give": "давать", "gave": "дал", "given": "данный",
    "giving": "давая",
    "put": "положить", "puts": "кладёт", "putting": "кладя",
    "set": "поставить", "sets": "ставит", "setting": "ставя",
    "place": "место", "placed": "поместил", "placing": "помещая",
    "keep": "хранить", "kept": "хранил", "keeping": "храня",
    "hold": "держать", "held": "держал", "holding": "держа",
    "let": "позволить", "lets": "позволяет",
    "begin": "начать", "began": "начал", "begun": "начатый",
    "beginning": "начало",
    "end": "конец", "ended": "закончился", "ending": "конечный",
    "finish": "завершить", "finished": "завершил",
    "open": "открыть", "opened": "открыл", "opening": "открывая",
    "close": "закрыть", "closed": "закрыл", "closing": "закрывая",
    "fill": "наполнить", "filled": "наполнил", "full": "полный",
    "empty": "пустой", "emptied": "опустошил",
    "build": "строить", "built": "построил", "building": "строя",
    "destroy": "уничтожить", "destroyed": "уничтожил",
    "destruction": "разрушение",
    "break": "разбить", "broke": "разбил", "broken": "сломанный",
    "breaking": "разбивая",
    "cut": "отрезать", "cuts": "режет", "cutting": "отрезая",
    "strike": "ударить", "struck": "ударил",
    "beat": "бить", "beaten": "побитый",
    "kill": "убить", "killed": "убил", "killing": "убивая",
    "slay": "умертвить", "slew": "умертвил", "slain": "убитый",
    "fight": "бороться", "fought": "боролся", "fighting": "борясь",
    "save": "спасти", "saved": "спасён", "saving": "спасая",
    "help": "помочь", "helped": "помог", "helping": "помогая",
    "protect": "защитить", "protected": "защитил",
    "hide": "скрыть", "hid": "скрыл", "hidden": "скрытый",
    "hiding": "скрывая",
    "show": "показать", "showed": "показал", "shown": "показанный",
    "showing": "показывая",
    "find": "найти", "found": "нашёл", "finding": "находя",
    "seek": "искать", "sought": "искал", "seeking": "ища",
    "search": "искать", "searched": "искал",
    "gather": "собирать", "gathered": "собрал", "gathering": "собирая",
    "scatter": "рассеять", "scattered": "рассеянный",
    "separate": "отделить", "separated": "отделил",
    "join": "присоединить", "joined": "присоединился",
    "divide": "разделить", "divided": "разделил",
    "unite": "объединить", "united": "объединился",
    "mix": "смешать", "mixed": "смешанный",
    "pour": "вылить", "poured": "вылил", "pouring": "выливая",
    "sprinkle": "окропить", "sprinkled": "окропил",
    "wash": "омыть", "washed": "омыл", "washing": "омывая",
    "cleanse": "очистить", "cleansed": "очистил",
    "purify": "очистить", "purified": "очищенный",
    "anoint": "помазать", "anointed": "помазанный",
    "heal": "исцелить", "healed": "исцелил", "healing": "исцеление",
    "restore": "восстановить", "restored": "восстановил",
    "raise": "поднять", "raised": "поднял", "raising": "поднимая",
    "lift": "поднять", "lifted": "поднял", "lifting": "поднимая",
    "stretch": "простереть", "stretched": "простёр",
    "touch": "коснуться", "touched": "коснулся",
    "seize": "схватить", "seized": "схватил",
    "catch": "поймать", "caught": "поймал",
    "throw": "бросить", "threw": "бросил", "thrown": "брошенный",
    "cast": "бросить",
    "receive": "принять", "received": "принял",
    "accept": "принять", "accepted": "принял",
    "offer": "приносить", "offered": "принёс", "offering": "приношение",
    "present": "представить", "presented": "представил",
    "prepare": "приготовить", "prepared": "приготовил",
    "write": "писать", "wrote": "написал", "written": "написанное",
    "writing": "пишущий",
    "read": "читать",
    "count": "считать", "counted": "считал",
    "number": "число", "numbered": "сосчитан",
    "measure": "измерить", "measured": "измерил",
    "weigh": "взвесить", "weighed": "взвесил",

    # Verbs - state/emotion
    "live": "жить", "lived": "жил", "living": "живущий",
    "die": "умереть", "died": "умер", "dying": "умирающий",
    "eat": "есть", "ate": "ел", "eaten": "съеденный",
    "eating": "ядущий",
    "drink": "пить", "drank": "пил", "drunk": "выпитый",
    "drinking": "пьющий",
    "sleep": "спать", "slept": "спал", "sleeping": "спящий",
    "wake": "проснуться", "woke": "проснулся",
    "love": "любить", "loved": "возлюбил", "loving": "любящий",
    "hate": "ненавидеть", "hated": "ненавидимый",
    "fear": "бояться", "feared": "боялся", "fearing": "боясь",
    "rejoice": "радоваться", "rejoiced": "возрадовался",
    "weep": "плакать", "wept": "плакал", "weeping": "плача",
    "mourn": "оплакивать", "mourned": "оплакивал",
    "mourning": "оплакивая",
    "grieve": "горевать", "grieved": "горевал",
    "suffer": "страдать", "suffered": "страдал",
    "suffering": "страдание",
    "trust": "уповать", "trusted": "уповал", "trusting": "уповая",
    "hope": "надеяться", "hoped": "надеялся",
    "desire": "желать", "desired": "желал",
    "want": "хотеть", "wanted": "хотел",
    "need": "нуждаться", "needed": "нуждался",
    "like": "подобный", "liked": "нравился",
    "wish": "желать", "wished": "пожелал",
    "enjoy": "наслаждаться", "enjoyed": "наслаждался",
    "please": "угодить", "pleased": "угодил",
    "able": "способный",
    "behooves": "надлежит",

    # Verbs - authority/worship
    "serve": "служить", "served": "служил", "serving": "служа",
    "worship": "поклоняться", "worshiped": "поклонился",
    "worshiping": "поклоняясь",
    "bow": "поклониться", "bowed": "поклонился",
    "bowing": "кланяясь",
    "kneel": "преклонить колени", "knelt": "преклонил",
    "obey": "повиноваться", "obeyed": "повиновался",
    "disobey": "ослушаться", "disobeyed": "ослушался",
    "rebel": "восставать", "rebelled": "восстал",
    "reign": "царствовать", "reigned": "царствовал",
    "reigning": "царствуя",
    "rule": "править", "ruled": "правил", "ruling": "правящий",
    "judge": "судить", "judged": "судил", "judging": "судя",
    "condemn": "осудить", "condemned": "осуждённый",
    "forgive": "простить", "forgave": "простил",
    "forgiveness": "прощение",
    "punish": "наказать", "punished": "наказал",
    "punishment": "наказание",
    "redeem": "искупить", "redeemed": "искупил",
    "inherit": "наследовать", "inherited": "наследовал",
    "inherit": "наследовать",
    "bless": "благословить", "blessed": "благословенный",
    "blessing": "благословение",
    "curse": "проклясть", "cursed": "проклятый",
    "consecrate": "посвятить", "consecrated": "посвящённый",
    "sanctify": "освятить", "sanctified": "освящённый",
    "baptize": "крестить", "baptized": "крещённый",
    "baptism": "крещение",
    "circumcise": "обрезать", "circumcised": "обрезанный",
    "circumcision": "обрезание",
    "sacrifice": "приносить жертву", "sacrificed": "принёс жертву",
    "atone": "искупить", "atonement": "искупление",
    "belongs": "принадлежит", "belong": "принадлежать",
    "belonged": "принадлежал",

    # Verbs - combat/agriculture
    "conquer": "победить", "conquered": "победил",
    "defeat": "поразить", "defeated": "поразил",
    "capture": "захватить", "captured": "захватил",
    "deliver": "избавить", "delivered": "избавил",
    "plunder": "грабить", "plundered": "ограбил",
    "devour": "поглотить", "devoured": "поглотил",
    "prevail": "одолеть", "prevailed": "одолел",
    "encamp": "расположиться станом", "encamped": "расположились станом",
    "camp": "стан",
    "besiege": "осаждать", "besieged": "осаждал",
    "sow": "сеять", "sowed": "сеял", "sown": "посеянный",
    "reap": "жать", "reaped": "жал",
    "harvest": "жатва", "plant": "посадить", "planted": "посадил",
    "plow": "пахать", "plowed": "пахал",
    "burn": "гореть", "burned": "сжёг", "burning": "горящий",
    "burnt": "сожжённый",
    "consume": "поглотить", "consumed": "поглощён",
    "perish": "погибнуть", "perished": "погиб",

    # Verbs - misc
    "beget": "родить", "begat": "родил", "begotten": "рождённый",
    "bear": "родить", "bore": "родила", "born": "рождённый",
    "conceive": "зачать", "conceived": "зачала",
    "name": "имя", "named": "назвал",
    "clothe": "облечь", "clothed": "облечённый",
    "cover": "покрыть", "covered": "покрыл", "covering": "покров",
    "uncover": "открыть", "uncovered": "открыл",
    "swallow": "поглотить", "swallowed": "поглотил",
    "multiply": "умножить", "multiplied": "умножил",
    "increase": "увеличить", "increased": "увеличил",
    "decrease": "уменьшить", "decreased": "уменьшил",
    "change": "изменить", "changed": "изменил",
    "create": "сотворить", "created": "сотворил",
    "form": "образовать", "formed": "образовал",
    "appear": "явиться", "appeared": "явился",
    "appearing": "являясь",
    "reveal": "открыть", "revealed": "открыл",
    "exist": "существовать", "existed": "существовал",
    "establish": "установить", "established": "установил",
    "confirm": "подтвердить", "confirmed": "подтвердил",
    "appoint": "назначить", "appointed": "назначил",
    "choose": "избрать", "chose": "избрал", "chosen": "избранный",
    "select": "выбрать", "selected": "выбрал",
    "cause": "причинить",
    "allow": "позволить", "allowed": "позволил",
    "forbid": "запретить", "forbade": "запретил",
    "refuse": "отказать", "refused": "отказал",
    "permit": "разрешить", "permitted": "разрешил",
    "prevent": "препятствовать", "prevented": "воспрепятствовал",
    "cease": "прекратить", "ceased": "прекратил",
    "possess": "владеть", "possessed": "владел",
    "dispossess": "изгнать",
    "dwell": "обитать", "dwelt": "обитал",
    "inhabit": "населять",
    "settle": "поселиться", "settled": "поселился",
    "wander": "блуждать", "wandered": "блуждал",

    # Nouns - body
    "head": "голова", "face": "лицо", "eye": "глаз", "eyes": "глаза",
    "ear": "ухо", "ears": "уши", "nose": "нос",
    "mouth": "уста", "lip": "губа", "lips": "губы",
    "tongue": "язык", "tooth": "зуб", "teeth": "зубы",
    "neck": "шея", "throat": "горло", "shoulder": "плечо",
    "shoulders": "плечи",
    "arm": "рука", "arms": "руки",
    "hand": "рука", "hands": "руки",
    "finger": "перст", "fingers": "персты",
    "palm": "ладонь", "fist": "кулак",
    "chest": "грудь", "breast": "грудь", "breasts": "грудь",
    "back": "спина", "belly": "чрево", "womb": "утроба",
    "loins": "чресла", "thigh": "бедро",
    "leg": "нога", "legs": "ноги",
    "foot": "нога", "feet": "ноги",
    "heel": "пята", "knee": "колено", "knees": "колени",
    "bone": "кость", "bones": "кости",
    "skin": "кожа", "flesh": "плоть", "blood": "кровь",
    "heart": "сердце", "hearts": "сердца",
    "soul": "душа", "souls": "души",
    "spirit": "дух", "spirits": "духи",
    "body": "тело", "bodies": "тела",
    "hair": "волосы",

    # Nouns - people
    "man": "человек", "men": "мужи", "male": "мужчина",
    "woman": "женщина", "women": "женщины", "female": "женщина",
    "child": "дитя", "children": "дети",
    "boy": "мальчик", "girl": "девочка",
    "lad": "юноша", "maiden": "дева",
    "youth": "юноша", "young": "молодой",
    "baby": "младенец", "infant": "младенец",
    "son": "сын", "sons": "сыновья",
    "daughter": "дочь", "daughters": "дочери",
    "father": "отец", "fathers": "отцы",
    "mother": "мать", "mothers": "матери",
    "brother": "брат", "brothers": "братья",
    "sister": "сестра", "sisters": "сёстры",
    "husband": "муж", "wife": "жена", "wives": "жёны",
    "family": "семья", "families": "семьи",
    "household": "домочадцы",
    "ancestors": "предки", "descendants": "потомки",
    "generation": "поколение", "generations": "поколения",
    "clan": "род", "clans": "роды",
    "tribe": "колено", "tribes": "колена",
    "people": "народ", "peoples": "народы",
    "nation": "народ", "nations": "народы",
    "race": "род",
    "foreigner": "чужеземец", "foreigners": "чужеземцы",
    "stranger": "пришелец", "strangers": "пришельцы",
    "neighbor": "ближний", "neighbors": "ближние",
    "friend": "друг", "friends": "друзья",
    "enemy": "враг", "enemies": "враги",
    "companion": "товарищ",
    "multitude": "множество", "crowd": "толпа", "crowds": "толпы",
    "assembly": "собрание", "congregation": "собрание",
    "firstborn": "первенец",
    "orphan": "сирота", "widow": "вдова", "widows": "вдовы",
    "poor": "бедный", "rich": "богатый",
    "wise": "мудрый", "foolish": "глупый", "fool": "глупец",
    "righteous": "праведный", "wicked": "нечестивый",
    "person": "лицо",
    "humankind": "человечество",
    "inhabitants": "жители",

    # Nouns - authority
    "king": "царь", "kings": "цари", "queen": "царица",
    "kingdom": "царство", "kingdoms": "царства",
    "prince": "князь", "princes": "князья",
    "princess": "княгиня",
    "lord": "господин", "lords": "господа",
    "master": "господин", "masters": "господа",
    "ruler": "правитель", "rulers": "правители",
    "leader": "вождь", "leaders": "вожди",
    "chief": "начальник", "chiefs": "начальники",
    "captain": "начальник",
    "commander": "военачальник", "commanders": "военачальники",
    "governor": "правитель", "governors": "правители",
    "official": "сановник", "officials": "сановники",
    "servant": "раб", "servants": "рабы",
    "slave": "раб", "slaves": "рабы",
    "maid": "служанка", "maidservant": "служанка",
    "messenger": "посланник", "messengers": "посланники",
    "herald": "вестник",
    "scribe": "книжник", "scribes": "книжники",
    "elder": "старейшина", "elders": "старейшины",

    # Nouns - religious
    "priest": "священник", "priests": "священники",
    "prophet": "пророк", "prophets": "пророки",
    "angel": "ангел", "angels": "ангелы",
    "apostle": "апостол", "apostles": "апостолы",
    "disciple": "ученик", "disciples": "ученики",
    "teacher": "учитель", "teachers": "учителя",
    "saint": "святой", "saints": "святые",
    "shepherd": "пастырь", "shepherds": "пастыри",
    "sinner": "грешник", "sinners": "грешники",
    "Levite": "Левит", "Levites": "Левиты",
    "Pharisee": "Фарисей", "Pharisees": "Фарисеи",
    "Sadducee": "Саддукей", "Sadducees": "Саддукеи",
    "cherub": "херувим", "cherubim": "херувимы",
    "seraph": "серафим", "seraphim": "серафимы",

    # Nouns - places/nature
    "God": "Бог", "god": "бог", "gods": "боги",
    "Lord": "Господь",
    "heaven": "небо", "heavens": "небеса",
    "earth": "земля", "land": "земля", "lands": "земли",
    "world": "мир",
    "sea": "море", "seas": "моря",
    "water": "вода", "waters": "воды",
    "river": "река", "rivers": "реки",
    "lake": "озеро", "pool": "водоём",
    "spring": "источник", "springs": "источники",
    "well": "колодец", "wells": "колодцы",
    "fountain": "источник",
    "mountain": "гора", "mountains": "горы",
    "hill": "холм", "hills": "холмы",
    "valley": "долина", "valleys": "долины",
    "plain": "равнина", "plains": "равнины",
    "wilderness": "пустыня", "desert": "пустыня",
    "forest": "лес", "woods": "леса",
    "field": "поле", "fields": "поля",
    "garden": "сад", "gardens": "сады",
    "vineyard": "виноградник", "vineyards": "виноградники",
    "pasture": "пастбище", "pastures": "пастбища",
    "rock": "скала", "rocks": "скалы",
    "stone": "камень", "stones": "камни",
    "sand": "песок", "dust": "прах", "clay": "глина",
    "ground": "земля",
    "island": "остров", "islands": "острова",
    "shore": "берег", "coast": "побережье",
    "cave": "пещера", "caves": "пещеры",
    "pit": "яма", "pits": "ямы",
    "grave": "гроб", "tomb": "гробница",
    "wadi": "вади",
    "surface": "поверхность",
    "region": "область", "regions": "области",
    "territory": "территория",
    "border": "граница", "borders": "границы",
    "boundary": "граница", "boundaries": "границы",
    "country": "страна",

    # Nouns - buildings
    "house": "дом", "houses": "дома",
    "city": "город", "cities": "города",
    "town": "городок", "towns": "городки",
    "village": "селение", "villages": "селения",
    "wall": "стена", "walls": "стены",
    "gate": "ворота", "gates": "ворота",
    "door": "дверь", "doors": "двери",
    "window": "окно", "windows": "окна",
    "tower": "башня", "towers": "башни",
    "fortress": "крепость",
    "palace": "дворец", "palaces": "дворцы",
    "temple": "храм", "temples": "храмы",
    "tabernacle": "скиния",
    "tent": "шатёр", "tents": "шатры",
    "altar": "жертвенник", "altars": "жертвенники",
    "throne": "престол", "thrones": "престолы",
    "pillar": "столб", "pillars": "столбы",
    "column": "колонна", "columns": "колонны",
    "foundation": "основание", "foundations": "основания",
    "courtyard": "двор",
    "roof": "крыша", "floor": "пол",
    "entrance": "вход", "exit": "выход",
    "synagogue": "синагога", "synagogues": "синагоги",
    "church": "церковь",
    "ark": "ковчег",
    "camp": "стан", "camps": "станы",

    # Nouns - objects
    "sword": "меч", "swords": "мечи",
    "spear": "копьё", "spears": "копья",
    "shield": "щит", "shields": "щиты",
    "bow": "лук", "arrow": "стрела", "arrows": "стрелы",
    "helmet": "шлем", "armor": "доспех",
    "chariot": "колесница", "chariots": "колесницы",
    "chariotry": "колесницы",
    "horse": "конь", "horses": "кони",
    "donkey": "осёл", "donkeys": "ослы",
    "camel": "верблюд", "camels": "верблюды",
    "ox": "вол", "oxen": "волы",
    "cow": "корова", "bull": "телец",
    "sheep": "овца", "lamb": "агнец", "lambs": "агнцы",
    "goat": "козёл", "goats": "козлы",
    "ram": "овен", "rams": "овны",
    "flock": "стадо", "flocks": "стада",
    "herd": "стадо", "herds": "стада",
    "cattle": "скот", "livestock": "скот",
    "animal": "животное", "animals": "животные",
    "beast": "зверь", "beasts": "звери",
    "bird": "птица", "birds": "птицы",
    "dove": "голубь", "eagle": "орёл",
    "raven": "ворон", "sparrow": "воробей",
    "fish": "рыба", "serpent": "змей", "dragon": "дракон",
    "lion": "лев", "lions": "львы",
    "bear": "медведь", "wolf": "волк",
    "dog": "пёс", "dogs": "псы",
    "tree": "дерево", "trees": "деревья",
    "vine": "виноградная лоза", "branch": "ветвь",
    "branches": "ветви",
    "leaf": "лист", "leaves": "листья",
    "root": "корень", "roots": "корни",
    "seed": "семя", "seeds": "семена",
    "fruit": "плод", "fruits": "плоды",
    "grain": "зерно", "wheat": "пшеница", "barley": "ячмень",
    "fig": "смоква",
    "olive": "маслина", "olives": "маслины",
    "bread": "хлеб", "loaf": "хлеб", "loaves": "хлебы",
    "wine": "вино", "oil": "елей",
    "honey": "мёд", "milk": "молоко",
    "salt": "соль", "vinegar": "уксус",
    "food": "пища", "meat": "мясо",
    "cup": "чаша", "cups": "чаши",
    "vessel": "сосуд", "vessels": "сосуды",
    "pot": "горшок", "jar": "кувшин",
    "basket": "корзина", "baskets": "корзины",
    "lamp": "светильник", "lamps": "светильники",
    "candle": "свеча",
    "key": "ключ", "keys": "ключи",
    "chain": "цепь", "chains": "цепи",
    "rope": "верёвка", "cord": "верёвка",
    "net": "сеть", "nets": "сети",
    "curtain": "завеса", "curtains": "завесы",
    "veil": "покрывало",
    "cloth": "ткань", "garment": "одежда", "garments": "одежды",
    "robe": "одеяние", "robes": "одеяния",
    "tunic": "хитон",
    "sandal": "сандалия", "sandals": "сандалии",
    "strap": "ремень",
    "crown": "венец", "crowns": "венцы",
    "ring": "кольцо", "rings": "кольца",
    "seal": "печать",
    "scroll": "свиток", "scrolls": "свитки",
    "book": "книга", "books": "книги",
    "letter": "послание", "letters": "послания",
    "tablet": "скрижаль", "tablets": "скрижали",
    "ephod": "ефод", "incense": "фимиам",
    "idol": "идол", "idols": "идолы",
    "image": "образ", "images": "образы",
    "molten": "литой",
    "cross": "крест",
    "coin": "монета", "coins": "монеты",
    "money": "деньги", "treasure": "сокровище",
    "gold": "золото", "silver": "серебро",
    "bronze": "медь", "iron": "железо",
    "copper": "медь", "brass": "латунь",
    "tin": "олово", "lead": "свинец",
    "wood": "дерево", "timber": "брёвна",
    "articles": "утварь",
    "shekel": "сикль", "shekels": "сиклей",
    "cubit": "локоть", "cubits": "локтей",

    # Nouns - abstract
    "word": "слово", "words": "слова",
    "name": "имя", "names": "имена",
    "voice": "голос", "voices": "голоса",
    "sound": "звук", "sounds": "звуки",
    "song": "песня", "songs": "песни",
    "prayer": "молитва", "prayers": "молитвы",
    "praise": "хвала",
    "sign": "знамение", "signs": "знамения",
    "wonder": "чудо", "wonders": "чудеса",
    "miracle": "чудо", "miracles": "чудеса",
    "power": "сила", "powers": "силы",
    "strength": "сила", "might": "мощь",
    "authority": "власть",
    "glory": "слава", "honor": "честь",
    "majesty": "величие",
    "grace": "благодать", "mercy": "милость",
    "kindness": "доброта",
    "compassion": "сострадание",
    "love": "любовь",
    "peace": "мир", "joy": "радость",
    "hope": "надежда", "faith": "вера",
    "truth": "истина", "wisdom": "мудрость",
    "knowledge": "знание",
    "counsel": "совет",
    "law": "закон", "laws": "законы",
    "commandment": "заповедь", "commandments": "заповеди",
    "statute": "устав", "statutes": "уставы",
    "decree": "указ", "decrees": "указы",
    "judgment": "суд", "judgments": "суды",
    "justice": "правосудие",
    "righteousness": "праведность",
    "holiness": "святость",
    "iniquity": "беззаконие", "iniquities": "беззакония",
    "sin": "грех", "sins": "грехи",
    "transgression": "преступление",
    "guilt": "вина", "innocent": "невиновный",
    "wickedness": "нечестие",
    "evil": "зло",
    "calamity": "бедствие",
    "trouble": "беда", "troubles": "беды",
    "harm": "вред",
    "suffering": "страдание",
    "death": "смерть", "life": "жизнь",
    "salvation": "спасение",
    "redemption": "искупление",
    "covenant": "завет", "covenants": "заветы",
    "promise": "обещание", "promises": "обещания",
    "oath": "клятва", "oaths": "клятвы",
    "sacrifice": "жертва", "sacrifices": "жертвы",
    "offering": "приношение", "offerings": "приношения",
    "contribution": "вклад",
    "gift": "дар", "gifts": "дары",
    "inheritance": "наследие",
    "possession": "владение", "possessions": "владения",
    "portion": "часть", "portions": "части",
    "share": "доля",
    "lot": "жребий", "lots": "жребии",
    "reward": "награда", "rewards": "награды",
    "wages": "плата",
    "age": "век", "ages": "века",
    "time": "время", "times": "времена",
    "season": "время",
    "day": "день", "days": "дни",
    "night": "ночь", "nights": "ночи",
    "morning": "утро", "evening": "вечер",
    "dawn": "заря", "dusk": "сумерки",
    "noon": "полдень", "midnight": "полночь",
    "hour": "час", "hours": "часы",
    "month": "месяц", "months": "месяцев",
    "year": "год", "years": "лет",
    "week": "неделя", "weeks": "недель",
    "perpetuity": "вечность", "eternity": "вечность",
    "antiquity": "древность",
    "way": "путь", "ways": "пути",
    "path": "путь", "paths": "пути",
    "road": "дорога", "roads": "дороги",
    "journey": "путешествие",
    "work": "дело", "works": "дела",
    "deed": "деяние", "deeds": "деяния",
    "act": "поступок", "acts": "поступки",
    "matter": "дело", "matters": "дела",
    "thing": "вещь", "things": "вещи",
    "part": "часть", "parts": "части",
    "rest": "остаток",
    "remnant": "остаток",
    "number": "число",
    "length": "длина", "breadth": "ширина",
    "height": "высота", "depth": "глубина",
    "weight": "вес", "measure": "мера",
    "side": "сторона", "sides": "стороны",
    "top": "вершина", "bottom": "дно",
    "middle": "середина",
    "corner": "угол", "corners": "углы",
    "north": "север", "south": "юг",
    "east": "восток", "west": "запад",
    "right": "правый", "left": "левый",
    "end": "конец", "beginning": "начало",
    "appearance": "вид",
    "vision": "видение", "visions": "видения",
    "dream": "сон", "dreams": "сны",
    "mystery": "тайна",
    "likeness": "подобие",
    "testimony": "свидетельство",
    "witness": "свидетель", "witnesses": "свидетели",
    "gospel": "евангелие",
    "teaching": "учение", "teachings": "учения",
    "parable": "притча", "parables": "притчи",
    "revelation": "откровение",
    "prophecy": "пророчество",
    "resurrection": "воскресение",
    "battle": "битва", "battles": "битвы",
    "war": "война", "wars": "войны",
    "army": "войско", "armies": "войска",
    "hosts": "воинства",
    "guard": "стража", "guards": "стражники",
    "violence": "насилие",
    "plague": "язва", "plagues": "язвы",
    "famine": "голод",
    "passover": "Пасха", "Passover": "Пасха",
    "feast": "праздник", "feasts": "праздники",
    "festival": "праздник",
    "sabbath": "суббота", "Sabbath": "Суббота",
    "favor": "благоволение",
    "loyalty": "верность",

    # Adjectives
    "good": "хороший", "bad": "плохой",
    "great": "великий", "small": "малый", "little": "малый",
    "big": "большой", "large": "большой",
    "long": "длинный", "short": "короткий",
    "high": "высокий", "low": "низкий",
    "deep": "глубокий", "wide": "широкий", "narrow": "узкий",
    "strong": "сильный", "weak": "слабый",
    "old": "старый", "new": "новый", "ancient": "древний",
    "young": "молодой",
    "hot": "горячий", "cold": "холодный", "warm": "тёплый",
    "dry": "сухой", "wet": "мокрый",
    "clean": "чистый", "unclean": "нечистый",
    "pure": "чистый", "impure": "нечистый",
    "holy": "святой", "sacred": "священный",
    "true": "истинный", "false": "ложный",
    "free": "свободный",
    "mighty": "могучий", "powerful": "сильный",
    "faithful": "верный",
    "beautiful": "красивый", "fair": "прекрасный",
    "pleasant": "приятный",
    "bitter": "горький", "sweet": "сладкий",
    "precious": "драгоценный",
    "desolate": "опустошённый",
    "barren": "бесплодный",
    "abundant": "обильный",
    "eternal": "вечный", "everlasting": "вечный",
    "former": "прежний",
    "latter": "последний",
    "unblemished": "без порока",
    "soothing": "приятное благоухание",
    "fine": "тонкий",
    "white": "белый", "black": "чёрный", "red": "красный",
    "green": "зелёный", "blue": "голубой", "purple": "пурпурный",
    "scarlet": "багряный",

    # Nature
    "fire": "огонь", "flame": "пламя", "flames": "пламя",
    "light": "свет", "darkness": "тьма",
    "sun": "солнце", "moon": "луна",
    "star": "звезда", "stars": "звёзды",
    "cloud": "облако", "clouds": "облака",
    "rain": "дождь", "snow": "снег", "hail": "град",
    "wind": "ветер", "winds": "ветры",
    "storm": "буря", "thunder": "гром", "lightning": "молния",
    "rainbow": "радуга",
    "flood": "потоп",
    "earthquake": "землетрясение",

    # Proper names
    "Yahweh": "Яхве", "God": "Бог", "Christ": "Христос",
    "Jesus": "Иисус", "Israel": "Израиль",
    "David": "Давид", "Moses": "Моисей", "Abraham": "Авраам",
    "Jacob": "Иаков", "Isaac": "Исаак", "Joseph": "Иосиф",
    "Judah": "Иуда", "Jerusalem": "Иерусалим",
    "Egypt": "Египет", "Babylon": "Вавилон", "Zion": "Сион",
    "Aaron": "Аарон", "Solomon": "Соломон", "Samuel": "Самуил",
    "Elijah": "Илия", "Elisha": "Елисей",
    "Joshua": "Иисус Навин", "Peter": "Пётр",
    "Paul": "Павел", "John": "Иоанн", "Simon": "Симон",
    "Mary": "Мария", "Satan": "Сатана", "Pharaoh": "Фараон",
    "Jordan": "Иордан", "Galilee": "Галилея", "Samaria": "Самария",
    "Benjamin": "Вениамин", "Levi": "Левий", "Dan": "Дан",
    "Ephraim": "Ефрем", "Manasseh": "Манассия",
    "Reuben": "Рувим", "Gad": "Гад", "Asher": "Асир",
    "Naphtali": "Неффалим", "Simeon": "Симеон",
    "Issachar": "Иссахар", "Zebulun": "Завулон",
    "Saul": "Саул", "Jonathan": "Ионафан",
    "Absalom": "Авессалом", "Daniel": "Даниил",
    "Isaiah": "Исаия", "Jeremiah": "Иеремия",
    "Ezekiel": "Иезекииль", "Hosea": "Осия",
    "Joel": "Иоиль", "Amos": "Амос", "Obadiah": "Авдий",
    "Jonah": "Иона", "Micah": "Михей", "Nahum": "Наум",
    "Habakkuk": "Аввакум", "Zephaniah": "Софония",
    "Haggai": "Аггей", "Zechariah": "Захария",
    "Malachi": "Малахия", "Noah": "Ной",
    "Adam": "Адам", "Eve": "Ева", "Sarah": "Сарра",
    "Rebecca": "Ревекка", "Rachel": "Рахиль", "Leah": "Лия",
    "Ruth": "Руфь", "Esther": "Есфирь", "Boaz": "Вооз",
    "Gideon": "Гедеон", "Samson": "Самсон", "Deborah": "Девора",
    "Hezekiah": "Езекия", "Josiah": "Иосия",
    "Nehemiah": "Неемия", "Ezra": "Ездра", "Job": "Иов",
    "Moab": "Моав", "Ammon": "Аммон", "Edom": "Едом",
    "Syria": "Сирия", "Assyria": "Ассирия", "Persia": "Персия",
    "Tyre": "Тир", "Sidon": "Сидон", "Gilead": "Галаад",
    "Lebanon": "Ливан", "Bethlehem": "Вифлеем",
    "Nazareth": "Назарет", "Capernaum": "Капернаум",
    "Canaan": "Ханаан", "Canaanites": "Хананеи",
    "Amorites": "Аморреи", "Hittites": "Хеттеи",
    "Philistines": "Филистимляне",
    "Chaldeans": "Халдеи",
    "Jews": "Иудеи", "Gentiles": "язычники",
    "Joab": "Иоав", "Aram": "Арам",
    "Damascus": "Дамаск",
    "Ahab": "Ахав", "Esau": "Исав",
    "Nebuchadnezzar": "Навуходоносор",
    "Jehoshaphat": "Иосафат",
    "Zedekiah": "Седекия",
    "Abram": "Аврам",
    "Ishmael": "Измаил",
    "Balaam": "Валаам", "Balak": "Валак",
    "Baal": "Ваал",
    "Abimelech": "Авимелех",
    "Eleazar": "Елеазар",
    "Abner": "Авенир",
    "Midian": "Мадиан",
    "Jehu": "Ииуй",
    "Asa": "Аса",
    "Jehoiada": "Иодай",
    "Joash": "Иоас",
    "Shechem": "Сихем",
    "Mordecai": "Мардохей",
    "Jesse": "Иессей",
    "Laban": "Лаван",
    "Ahaz": "Ахаз",
    "Haman": "Аман",
    "Hadad": "Адад",
    "Jehoiakim": "Иоаким",
    "Uriah": "Урия",
    "Sheba": "Сава",
    "Jericho": "Иерихон",
    "Beth": "Беф",
    "Judea": "Иудея",
    "Rehoboam": "Ровоам", "Jeroboam": "Иеровоам",
    "Andrew": "Андрей", "Philip": "Филипп",
    "Thomas": "Фома", "James": "Иаков",
    "Barnabas": "Варнава", "Timothy": "Тимофей",
    "Pilate": "Пилат", "Herod": "Ирод",
    "Amen": "Аминь", "amen": "аминь",
    "Hallelujah": "Аллилуия", "Selah": "Селах",
    "Rabbi": "Равви",

    # Special suffix/prefix patterns
    "-ward": "сторону",
    "-wards": "сторону",
    "-lehem": "-лехем",
    "-el": "-ел",
    "longer": "более",
    "sake": "ради",
    "account": "счёт",
    "view": "виду",
    "abundance": "изобилие",
    "midst": "среде",
    "meet": "навстречу",
    "flour": "мука",
    "unleavened": "пресный",
    "breads": "хлебы",

    "O": "О",
    "Word": "Слово",

    # Additional high-frequency words
    "will": "будет",
    "aside": "в сторону",
    "afraid": "боящийся",
    "offspring": "потомство",
    "smoke": "дым",
    "caused": "произвёл",
    "ashamed": "посрамлённый",
    "fat": "тук",
    "spread": "распростёр",
    "woe": "горе", "Woe": "Горе",
    "distress": "скорбь",
    "exile": "изгнание", "exiled": "изгнанный",
    "complete": "завершённый", "completed": "завершённый",
    "acted": "поступил",
    "relatives": "родственники",
    "round": "вокруг",
    "rage": "ярость",
    "enrolled": "исчисленный",
    "faithfulness": "верность",
    "willing": "желающий",
    "shame": "стыд",
    "observe": "соблюдать",
    "labor": "труд",
    "thanks": "благодарение",
    "remove": "удалить", "removed": "удалил",
    "laid": "положил",
    "shut": "затворить",
    "satisfied": "насытившийся",
    "early": "рано",
    "prostitute": "блудница",
    "refuge": "убежище",
    "pay": "заплатить",
    "pieces": "куски",
    "bound": "связанный",
    "produce": "произвести",
    "beloved": "возлюбленный",
    "wait": "ждать",
    "sojourner": "пришелец",
    "stuff": "вещи",
    "birth": "рождение",
    "sanctuary": "святилище",
    "room": "комната", "rooms": "комнаты",
    "wings": "крылья",
    "believing": "верующий",
    "silent": "молчащий",
    "torn": "разодранный",
    "rejected": "отвергнутый",
    "upright": "праведный",
    "waste": "пустошь",
    "heed": "внимание",
    "abomination": "мерзость", "abominations": "мерзости",
    "splendor": "великолепие",
    "grow": "расти",
    "guilty": "виновный",
    "tear": "разодрать",
    "while": "пока",
    "bed": "постель",
    "report": "весть",
    "breath": "дыхание",
    "heavy": "тяжёлый",
    "care": "забота",
    "horn": "рог", "horns": "рога",
    "fulfilled": "исполненный",
    "nakedness": "нагота",
    "greatness": "величие",
    "desolation": "запустение",
    "sold": "продал",
    "happen": "случиться", "happened": "случилось",
    "reproach": "поношение",
    "staff": "посох",
    "next": "следующий",
    "pole": "шест", "poles": "шесты",
    "case": "случай",
    "may": "да",
    "ephah": "ефа",
    "add": "прибавить",
    "gain": "приобрести",
    "prophesy": "пророчествовать",
    "direction": "направление",
    "angry": "гневный",
    "almighty": "Вседержитель", "Almighty": "Вседержитель",
    "dread": "ужас",
    "repeat": "повторить", "repeated": "повторил",
    "test": "испытать",
    "slaughter": "заклание",
    "quickly": "быстро",
    "weary": "утомлённый",
    "base": "основание", "bases": "основания",
    "human": "человеческий",
    "inner": "внутренний",
    "yoke": "ярмо",
    "distance": "расстояние",
    "trumpet": "труба", "trumpets": "трубы",
    "sheol": "Шеол", "Sheol": "Шеол",
    "needy": "нуждающийся",
    "strengthened": "укрепил",
    "repay": "воздать",
    "disease": "болезнь", "diseases": "болезни",
    "terror": "ужас",
    "aloud": "громко",
    "numerous": "многочисленный",
    "likewise": "подобно",
    "siege": "осада",
    "visit": "посетить",
    "escaped": "спасся",
    "court": "двор",
    "fellow": "ближний",
    "afflicted": "угнетённый", "affliction": "скорбь",
    "conduct": "поведение",
    "forsaken": "оставленный",
    "pleasure": "удовольствие",
    "bearing": "несущий",
    "step": "шаг", "steps": "шаги",
    "odor": "благоухание",
    "pride": "гордость",
    "fast": "пост",
    "prison": "темница",
    "buy": "купить",
    "comfort": "утешить",
    "boast": "хвалиться",
    "necessary": "необходимый",
    "kind": "род",
    "dried": "высохший",
    "beauty": "красота",
    "threshing": "гумно",
    "remembrance": "память",
    "horseman": "всадник", "horsemen": "всадники",
    "delight": "наслаждение",
    "blameless": "непорочный",
    "wild": "дикий",
    "presence": "присутствие",
    "deceit": "обман",
    "stumble": "споткнуться",
    "wave": "волна",
    "totally": "полностью",
    "exalted": "превознесённый",
    "pestilence": "мор",
    "sackcloth": "вретище",
    "mind": "ум",
    "escape": "спастись",
    "borne": "рождённый",
    "vengeance": "отмщение",
    "company": "сонм",
    "moved": "двинулся",
    "loud": "громкий",
    "abandoned": "оставил",
    "tore": "разодрал",
    "distant": "далёкий",
    "thorns": "тернии",
    "futility": "суета",
    "warrior": "воин", "warriors": "воины",
    "ancestor": "предок",
    "forgiven": "прощённый",
    "discipline": "наставление",
    "grass": "трава",
    "street": "улица", "streets": "улицы",
    "crushed": "сокрушённый",
    "security": "безопасность",
    "violet": "голубая",
    "plan": "замысел",
    "shaken": "потрясённый",
    "astray": "заблуждение",
    "bar": "засов", "bars": "засовы",
    "burden": "бремя",
    "upper": "верхний",
    "assembled": "собрались",
    "greet": "приветствовать",
    "longer": "более",
    "declaration": "изречение", "declarations": "изречения",
    "lampstand": "светильник",
    "worthlessness": "ничтожество",
    "foreignness": "чужбина",
    "bodyguard": "телохранитель", "bodyguards": "телохранители",
    "reeds": "тростник",
    "bowl": "чаша",
    "killer": "убийца",
    "acacia": "акация",
    "locusts": "саранча",
    "parents": "родители",
    "injustice": "несправедливость",
    "completeness": "полнота", "fullness": "полнота",
    "sojourners": "пришельцы",
    "Sinai": "Синай", "Sodom": "Содом",
    "Hebron": "Хеврон", "Gibeah": "Гива",
    "Mizpah": "Мицпа",
    "Nathan": "Нафан", "Benaiah": "Ванея",
    "Zadok": "Садок", "Hamath": "Емаф",
    "Gedaliah": "Годолия", "Shaphan": "Сафан",
    "Ahaziah": "Охозия", "Eli": "Илий",
    "Sihon": "Сигон", "Baasha": "Вааса",
    "Caleb": "Халев", "Azariah": "Азария",
    "Asaph": "Асаф", "Jephthah": "Иеффай",
    "Amaziah": "Амасия", "Ahasuerus": "Артаксеркс",
    "Hilkiah": "Хелкия", "Nun": "Навин",
    "Ben": "Бен", "Ai": "Гай",
    "Bashan": "Васан",
    "Philistine": "Филистимлянин",
    "placed": "поместил",
    "swore": "клялся",
    "upwards": "вверх",
    "to death": "к смерти",
    "put to death": "предан смерти",
    "afraid": "боящийся",
    "be afraid": "бояться",
    "thousand<s>": "тысячи",
    
    # Final batch
    "attention": "внимание", "hard": "жёсткий",
    "preserve": "сохранить", "preserved": "сохранил",
    "dark": "тёмный", "humble": "смиренный", "humbled": "смирился",
    "cedar": "кедр", "cedars": "кедры",
    "prophesied": "пророчествовал", "prophesying": "пророчествуя",
    "bosom": "лоно", "blast": "дуновение",
    "vow": "обет", "vows": "обеты",
    "profane": "осквернять", "profaned": "осквернён",
    "hungry": "голодный", "military": "военный",
    "front": "перед", "testimonies": "свидетельства",
    "profit": "польза", "overlaid": "обложил",
    "detestable": "мерзкий", "sojourn": "странствовать",
    "heat": "зной", "adultery": "прелюбодеяние",
    "singer": "певец", "singers": "певцы",
    "pleasing": "угодный", "porch": "притвор",
    "jealousy": "ревность", "often": "часто",
    "line": "верёвка", "repaired": "починил",
    "dug": "выкопал", "uncircumcised": "необрезанный",
    "rod": "жезл", "manner": "образ",
    "bury": "похоронить", "buried": "похоронен",
    "sealed": "запечатан", "drive": "гнать", "drove": "изгнал",
    "yes": "да", "bind": "связать",
    "fatherless": "сирота",
    "honored": "почтенный", "pain": "боль",
    "tremble": "трепетать", "trembled": "затрепетал",
    "crucified": "распят", "crucify": "распять",
    "toil": "труд", "virgin": "дева", "virgins": "девы",
    "snare": "сеть", "provoke": "разгневать",
    "once": "однажды", "arrived": "прибыл",
    "ship": "корабль", "ships": "корабли",
    "met": "встретил", "deliverer": "избавитель",
    "oppressed": "угнетённый", "flowing": "текущий",
    "treacherously": "вероломно", "grape": "виноград", "grapes": "виноград",
    "prostitution": "блуд",
    "weapon": "оружие", "weapons": "оружие",
    "corpse": "труп", "corpses": "трупы",
    "despised": "презренный", "hired": "наёмный",
    "lacking": "лишённый", "justified": "оправдан",
    "immorality": "разврат", "bought": "купил",
    "firm": "твёрдый", "devil": "дьявол",
    "frame": "рама", "frames": "рамы",
    "yes": "да", "ago": "тому назад",
    "Asherah": "Ашера",
    "Amalek": "Амалик", "Seir": "Сеир",
    "Gilgal": "Галгал", "Gibeon": "Гаваон",
    "Ramah": "Рама", "Negev": "Негев",
    "Gath": "Геф", "Shimei": "Семей",
    "Kiriath": "Кириаф", "Beer": "Беер",
    "Shemaiah": "Шемаия",
    "attention": "внимание",
    "ago": "назад",
    "hand": "рука", "hands": "руки",
    "forth": "вперёд",
    "swear": "клясться",
    "afraid": "боящийся",
    "will": "будет",
    "shall": "будет",
    "be": "быть",
    "is": "есть",
    "are": "суть",
    "were": "были",
    "was": "был",
    "been": "был",
    "has": "имеет",
    "have": "имеют",
    "had": "имел",
    "did": "сделал",
    "does": "делает",
    "the": "",
    "to": "к",
    "of": "",
    "in": "в",
    "for": "для",
    "as": "как",
    "an": "",
    "a": "",
    "it": "оно",
    "he": "он",
    "you": "ты",
    "not": "не",
    "that": "что",
    "s": "",
    "es": "",
    "I": "я",
    "blood": "кровь",
    "law": "закон",
    "put": "положить",
    "death": "смерть",
    "four": "четыре",
}

PUNCT_RE = re.compile(r'^(.*?)([.,;:!?¶]+)$')


def translate_gloss(gloss: str) -> str:
    if not gloss or gloss.strip() == '':
        return ''
    
    # Direct match first
    if gloss in WORD_MAP:
        return WORD_MAP[gloss]

    # Handle "/ " separator (STEPBible compound glosses)
    if '/ ' in gloss:
        parts = gloss.split('/ ')
        translated = [translate_fragment(p.strip()) for p in parts]
        result = ', '.join(t for t in translated if t)
        return result if result else gloss

    return translate_fragment(gloss)


def translate_fragment(g: str) -> str:
    if g in WORD_MAP:
        return WORD_MAP[g]
    
    # Strip trailing punctuation
    m = PUNCT_RE.match(g)
    if m:
        core, punct = m.group(1), m.group(2)
        tr = translate_fragment(core)
        if tr != core:
            return tr + punct

    # Strip angle brackets
    stripped = re.sub(r'[<>]', '', g).strip()
    if stripped and stripped in WORD_MAP:
        return WORD_MAP[stripped]
    
    # Try lowercase
    low = g.lower()
    if low in WORD_MAP:
        r = WORD_MAP[low]
        if g and g[0].isupper() and r:
            return r[0].upper() + r[1:]
        return r

    # Strip <> then try lowercase
    stripped_low = stripped.lower() if stripped else ''
    if stripped_low and stripped_low in WORD_MAP:
        r = WORD_MAP[stripped_low]
        if stripped and stripped[0].isupper() and r:
            return r[0].upper() + r[1:]
        return r
    
    # Plurals: try without 's' suffix
    if low.endswith('s') and len(low) > 3:
        singular = low[:-1]
        if singular in WORD_MAP:
            return WORD_MAP[singular]
        if singular.endswith('e') and singular[:-1] in WORD_MAP:
            return WORD_MAP[singular[:-1]]

    # Word-by-word for phrases
    words = g.split()
    if 1 < len(words) <= 6:
        translated = []
        any_tr = False
        for w in words:
            tr = translate_fragment(w)
            if tr != w:
                any_tr = True
                if tr:
                    translated.append(tr)
            else:
                translated.append(w)
        if any_tr:
            return ' '.join(translated)
    
    return g


def main():
    import sys
    base = os.path.join(os.path.dirname(os.path.abspath(__file__)), '..', 
                        'app', 'src', 'main', 'assets', 'bible', 'PODSTR')
    files = sorted(glob.glob(os.path.join(base, '*.json')))
    
    total = 0
    translated = 0
    latin_re = re.compile(r'[a-zA-Z]')
    still_latin = 0
    
    for fp in files:
        with open(fp) as f:
            data = json.load(f)
        
        modified = False
        for ch in data['book']['chapters']:
            for v in ch['verses']:
                for w in v.get('words', []):
                    total += 1
                    orig = w['r']
                    new = translate_gloss(orig)
                    if new != orig:
                        w['r'] = new
                        translated += 1
                        modified = True
                    if new and latin_re.search(new):
                        still_latin += 1
        
        if modified:
            with open(fp, 'w', encoding='utf-8') as f:
                json.dump(data, f, ensure_ascii=False, indent=None, separators=(',', ':'))
        
        print(f"  {os.path.basename(fp)}: done", file=sys.stderr)
    
    pct_done = 100 * (total - still_latin) / total if total else 0
    print(f"\nTranslated {translated}/{total} this pass")
    print(f"Still with Latin: {still_latin} ({100*still_latin/total:.1f}%)")
    print(f"Fully Russian: {total - still_latin} ({pct_done:.1f}%)")


if __name__ == '__main__':
    main()
