#!/usr/bin/env python3
"""Replace English glosses with Russian translations in PODSTR JSON files."""
import json
import glob
import os
import re

EN_TO_RU = {
    "the": "",
    "<the>": "",
    "a": "",
    "an": "",
    "[доп.]": "",
    "and": "и",
    "And": "И",
    "and/": "и/",
    "or": "или",
    "Or": "Или",
    "but": "но",
    "But": "Но",
    "not": "не",
    "Not": "Не",
    "no": "нет",
    "No": "Нет",
    "if": "если",
    "If": "Если",
    "then": "тогда",
    "Then": "Тогда",
    "that": "что",
    "That": "Что",
    "which": "который",
    "who": "кто",
    "whom": "кого",
    "whose": "чей",
    "what": "что",
    "when": "когда",
    "When": "Когда",
    "where": "где",
    "Where": "Где",
    "how": "как",
    "How": "Как",
    "why": "почему",
    "Why": "Почему",
    "to": "к",
    "for": "для",
    "For": "Для",
    "from": "от",
    "From": "От",
    "with": "с",
    "in": "в",
    "In": "В",
    "into": "в",
    "on": "на",
    "upon": "на",
    "over": "над",
    "under": "под",
    "before": "перед",
    "Before": "Перед",
    "after": "после",
    "After": "После",
    "until": "до",
    "between": "между",
    "among": "среди",
    "against": "против",
    "about": "о",
    "through": "через",
    "by": "через",
    "of": "",
    "of the": "",
    "out of": "из",
    "because": "потому что",
    "because of": "из-за",
    "also": "также",
    "also/": "также/",
    "now": "ныне",
    "Now": "Ныне",
    "here": "здесь",
    "there": "там",
    "this": "это",
    "This": "Это",
    "these": "эти",
    "those": "те",
    "thus": "так",
    "Thus": "Так",
    "so": "так",
    "So": "Так",
    "very": "очень",
    "much": "много",
    "many": "много",
    "more": "более",
    "most": "наиболее",
    "great": "великий",
    "all": "все",
    "All": "Все",
    "every": "каждый",
    "each": "каждый",
    "one": "один",
    "two": "два",
    "three": "три",
    "four": "четыре",
    "five": "пять",
    "six": "шесть",
    "seven": "семь",
    "eight": "восемь",
    "nine": "девять",
    "ten": "десять",
    "twelve": "двенадцать",
    "twenty": "двадцать",
    "thirty": "тридцать",
    "forty": "сорок",
    "fifty": "пятьдесят",
    "hundred": "сто",
    "thousand": "тысяча",
    "I": "я",
    "me": "меня",
    "my": "мой",
    "we": "мы",
    "us": "нас",
    "our": "наш",
    "you": "ты",
    "your": "твой",
    "he": "он",
    "He": "Он",
    "him": "его",
    "his": "его",
    "she": "она",
    "She": "Она",
    "her": "её",
    "it": "оно",
    "they": "они",
    "They": "Они",
    "them": "их",
    "their": "их",
    "himself": "себя",
    "herself": "себя",
    "themselves": "себя",
    "be": "быть",
    "is": "есть",
    "was": "был",
    "were": "были",
    "will be": "будет",
    "has been": "был",
    "have been": "были",
    "being": "будучи",
    "am": "есмь",
    "are": "есть",
    "do": "делать",
    "does": "делает",
    "did": "сделал",
    "done": "сделано",
    "make": "делать",
    "made": "сделал",
    "go": "идти",
    "Go": "Иди",
    "went": "пошёл",
    "gone": "ушёл",
    "going": "идущий",
    "come": "прийти",
    "Come": "Приди",
    "came": "пришёл",
    "coming": "приходящий",
    "say": "сказать",
    "said": "сказал",
    "saying": "говоря",
    "says": "говорит",
    "speak": "говорить",
    "spoke": "говорил",
    "spoken": "сказанное",
    "word": "слово",
    "words": "слова",
    "see": "видеть",
    "saw": "увидел",
    "seen": "виденное",
    "look": "смотри",
    "Look": "Смотри",
    "behold": "вот",
    "Behold": "Вот",
    "hear": "слышать",
    "heard": "услышал",
    "know": "знать",
    "knew": "знал",
    "known": "известный",
    "knowledge": "знание",
    "think": "думать",
    "thought": "мысль",
    "give": "давать",
    "gave": "дал",
    "given": "данный",
    "take": "взять",
    "took": "взял",
    "taken": "взятый",
    "put": "положить",
    "set": "поставить",
    "send": "послать",
    "sent": "послал",
    "bring": "принести",
    "brought": "принёс",
    "call": "звать",
    "called": "названный",
    "name": "имя",
    "names": "имена",
    "turn": "повернуть",
    "turned": "повернул",
    "return": "возвратиться",
    "returned": "возвратился",
    "stand": "стоять",
    "stood": "стоял",
    "sit": "сидеть",
    "sat": "сидел",
    "rise": "встать",
    "rose": "встал",
    "risen": "воскресший",
    "fall": "упасть",
    "fell": "упал",
    "fallen": "падший",
    "eat": "есть",
    "ate": "ел",
    "drink": "пить",
    "drank": "пил",
    "live": "жить",
    "lived": "жил",
    "life": "жизнь",
    "die": "умереть",
    "died": "умер",
    "dead": "мёртвый",
    "death": "смерть",
    "kill": "убить",
    "killed": "убит",
    "fight": "бороться",
    "war": "война",
    "peace": "мир",
    "love": "любовь",
    "loved": "возлюбил",
    "hate": "ненавидеть",
    "hated": "ненавидимый",
    "fear": "страх",
    "feared": "боялся",
    "hope": "надежда",
    "faith": "вера",
    "believe": "верить",
    "believed": "поверил",
    "trust": "доверять",
    "pray": "молиться",
    "prayed": "молился",
    "prayer": "молитва",
    "praise": "хвала",
    "bless": "благословить",
    "blessed": "благословенный",
    "blessing": "благословение",
    "curse": "проклятие",
    "cursed": "проклятый",
    "sin": "грех",
    "sinned": "согрешил",
    "sinner": "грешник",
    "righteous": "праведный",
    "righteousness": "праведность",
    "holy": "святой",
    "Holy": "Святой",
    "holiness": "святость",
    "clean": "чистый",
    "unclean": "нечистый",
    "good": "хороший",
    "Good": "Хороший",
    "evil": "зло",
    "Evil": "Зло",
    "true": "истинный",
    "truth": "истина",
    "false": "ложный",
    "lie": "ложь",
    "wisdom": "мудрость",
    "wise": "мудрый",
    "foolish": "глупый",
    "strong": "сильный",
    "strength": "сила",
    "weak": "слабый",
    "power": "сила",
    "glory": "слава",
    "Glory": "Слава",
    "honor": "честь",
    "majesty": "величие",
    "grace": "благодать",
    "mercy": "милость",
    "compassion": "сострадание",
    "kindness": "доброта",
    "anger": "гнев",
    "wrath": "гнев",
    "joy": "радость",
    "rejoice": "радоваться",
    "glad": "рад",
    "sorrow": "печаль",
    "weep": "плакать",
    "wept": "плакал",
    "cry": "вопиять",
    "cried": "воззвал",
    "voice": "голос",
    "mouth": "уста",
    "tongue": "язык",
    "eye": "глаз",
    "eyes": "глаза",
    "ear": "ухо",
    "ears": "уши",
    "face": "лицо",
    "hand": "рука",
    "hands": "руки",
    "foot": "нога",
    "feet": "ноги",
    "head": "голова",
    "heart": "сердце",
    "soul": "душа",
    "spirit": "дух",
    "Spirit": "Дух",
    "body": "тело",
    "flesh": "плоть",
    "blood": "кровь",
    "bone": "кость",
    "bones": "кости",
    "man": "человек",
    "men": "люди",
    "woman": "женщина",
    "women": "женщины",
    "child": "дитя",
    "children": "дети",
    "son": "сын",
    "sons": "сыновья",
    "daughter": "дочь",
    "daughters": "дочери",
    "father": "отец",
    "Father": "Отец",
    "mother": "мать",
    "brother": "брат",
    "brothers": "братья",
    "sister": "сестра",
    "family": "семья",
    "people": "народ",
    "nation": "народ",
    "nations": "народы",
    "king": "царь",
    "King": "Царь",
    "kingdom": "царство",
    "prince": "князь",
    "lord": "господин",
    "Lord": "Господь",
    "master": "господин",
    "servant": "раб",
    "servants": "рабы",
    "slave": "раб",
    "priest": "священник",
    "priests": "священники",
    "prophet": "пророк",
    "prophets": "пророки",
    "angel": "ангел",
    "angels": "ангелы",
    "apostle": "апостол",
    "disciple": "ученик",
    "disciples": "ученики",
    "teacher": "учитель",
    "judge": "судья",
    "judgment": "суд",
    "law": "закон",
    "Law": "Закон",
    "command": "повеление",
    "commandment": "заповедь",
    "commandments": "заповеди",
    "covenant": "завет",
    "promise": "обещание",
    "salvation": "спасение",
    "save": "спасти",
    "saved": "спасённый",
    "savior": "спаситель",
    "Savior": "Спаситель",
    "redeem": "искупить",
    "redeemer": "искупитель",
    "forgive": "простить",
    "forgiveness": "прощение",
    "sacrifice": "жертва",
    "offering": "приношение",
    "altar": "жертвенник",
    "temple": "храм",
    "Temple": "Храм",
    "church": "церковь",
    "synagogue": "синагога",
    "house": "дом",
    "houses": "дома",
    "city": "город",
    "cities": "города",
    "land": "земля",
    "earth": "земля",
    "Earth": "Земля",
    "world": "мир",
    "heaven": "небо",
    "heavens": "небеса",
    "Heaven": "Небо",
    "sky": "небо",
    "sea": "море",
    "water": "вода",
    "waters": "воды",
    "river": "река",
    "mountain": "гора",
    "mountains": "горы",
    "hill": "холм",
    "valley": "долина",
    "wilderness": "пустыня",
    "desert": "пустыня",
    "field": "поле",
    "garden": "сад",
    "tree": "дерево",
    "trees": "деревья",
    "vine": "виноградная лоза",
    "fruit": "плод",
    "seed": "семя",
    "bread": "хлеб",
    "wine": "вино",
    "oil": "елей",
    "fire": "огонь",
    "light": "свет",
    "Light": "Свет",
    "darkness": "тьма",
    "day": "день",
    "days": "дни",
    "night": "ночь",
    "morning": "утро",
    "evening": "вечер",
    "time": "время",
    "times": "времена",
    "year": "год",
    "years": "годы",
    "month": "месяц",
    "beginning": "начало",
    "end": "конец",
    "way": "путь",
    "road": "дорога",
    "path": "путь",
    "door": "дверь",
    "gate": "ворота",
    "gates": "ворота",
    "stone": "камень",
    "stones": "камни",
    "rock": "скала",
    "gold": "золото",
    "silver": "серебро",
    "iron": "железо",
    "sword": "меч",
    "shield": "щит",
    "bow": "лук",
    "arrow": "стрела",
    "horse": "конь",
    "donkey": "осёл",
    "sheep": "овца",
    "lamb": "агнец",
    "Lamb": "Агнец",
    "ox": "вол",
    "cattle": "скот",
    "bird": "птица",
    "birds": "птицы",
    "fish": "рыба",
    "cloth": "одежда",
    "garment": "одежда",
    "robe": "одеяние",
    "crown": "венец",
    "cross": "крест",
    "book": "книга",
    "letter": "послание",
    "sign": "знамение",
    "wonder": "чудо",
    "wonders": "чудеса",
    "miracle": "чудо",
    "nothing": "ничто",
    "something": "нечто",
    "everything": "всё",
    "never": "никогда",
    "always": "всегда",
    "forever": "вовек",
    "today": "сегодня",
    "tomorrow": "завтра",
    "yesterday": "вчера",
    "new": "новый",
    "old": "старый",
    "ancient": "древний",
    "young": "молодой",
    "first": "первый",
    "last": "последний",
    "other": "другой",
    "another": "другой",
    "same": "тот же",
    "own": "свой",
    "only": "только",
    "Only": "Только",
    "again": "снова",
    "still": "ещё",
    "yet": "ещё",
    "already": "уже",
    "even": "даже",
    "indeed": "поистине",
    "truly": "истинно",
    "Truly": "Истинно",
    "surely": "воистину",
    "perhaps": "может быть",
    "like": "как",
    "as": "как",
    "As": "Как",
    "than": "чем",
    "whether": "ли",
    "either": "либо",
    "neither": "ни",
    "nor": "ни",
    "both": "оба",
    "rather": "скорее",
    "enough": "довольно",
    "too": "тоже",
    "well": "хорошо",
    "right": "правый",
    "left": "левый",
    "up": "вверх",
    "down": "вниз",
    "above": "наверху",
    "below": "внизу",
    "near": "вблизи",
    "far": "далеко",
    "away": "прочь",
    "back": "назад",
    "together": "вместе",
    "apart": "отдельно",
    "alone": "один",
    "therefore": "потому",
    "Therefore": "Потому",
    "however": "однако",
    "However": "Однако",
    "nevertheless": "тем не менее",
    "Moreover": "Сверх того",
    "Yahweh": "Яхве",
    "God": "Бог",
    "Christ": "Христос",
    "Jesus": "Иисус",
    "Israel": "Израиль",
    "David": "Давид",
    "Moses": "Моисей",
    "Abraham": "Авраам",
    "Jacob": "Иаков",
    "Isaac": "Исаак",
    "Joseph": "Иосиф",
    "Judah": "Иуда",
    "Jerusalem": "Иерусалим",
    "Egypt": "Египет",
    "Babylon": "Вавилон",
    "Zion": "Сион",
    "Aaron": "Аарон",
    "Solomon": "Соломон",
    "Samuel": "Самуил",
    "Elijah": "Илия",
    "Joshua": "Иисус Навин",
    "Peter": "Пётр",
    "Paul": "Павел",
    "John": "Иоанн",
    "Simon": "Симон",
    "Mary": "Мария",
    "Satan": "Сатана",
    "Pharaoh": "Фараон",
    "Jordan": "Иордан",
    "Galilee": "Галилея",
    "Samaria": "Самария",
    "Philistines": "Филистимляне",
    "Benjamin": "Вениамин",
    "Levi": "Левий",
    "Dan": "Дан",
    "Ephraim": "Ефрем",
    "Manasseh": "Манассия",
    "Reuben": "Рувим",
    "Gad": "Гад",
    "Asher": "Асир",
    "Naphtali": "Неффалим",
    "Simeon": "Симеон",
    "Issachar": "Иссахар",
    "Zebulun": "Завулон",
    "Saul": "Саул",
    "Jonathan": "Ионафан",
    "Absalom": "Авессалом",
    "Daniel": "Даниил",
    "Isaiah": "Исаия",
    "Jeremiah": "Иеремия",
    "Ezekiel": "Иезекииль",
    "Hosea": "Осия",
    "Joel": "Иоиль",
    "Amos": "Амос",
    "Obadiah": "Авдий",
    "Jonah": "Иона",
    "Micah": "Михей",
    "Nahum": "Наум",
    "Habakkuk": "Аввакум",
    "Zephaniah": "Софония",
    "Haggai": "Аггей",
    "Zechariah": "Захария",
    "Malachi": "Малахия",
    "Noah": "Ной",
    "Adam": "Адам",
    "Eve": "Ева",
    "Sarah": "Сарра",
    "Rebecca": "Ревекка",
    "Rachel": "Рахиль",
    "Leah": "Лия",
    "Ruth": "Руфь",
    "Esther": "Есфирь",
    "Boaz": "Вооз",
    "Gideon": "Гедеон",
    "Samson": "Самсон",
    "Deborah": "Девора",
    "Hezekiah": "Езекия",
    "Josiah": "Иосия",
    "Nehemiah": "Неемия",
    "Ezra": "Ездра",
    "Job": "Иов",
    "Amen": "Аминь",
    "amen": "аминь",
    "Hallelujah": "Аллилуия",
    "Selah": "Селах",
    # Additional words
    "thing": "вещь",
    "things": "вещи",
    "Word": "Слово",
    "word,": "слово,",
    "Word,": "Слово,",
    "Word.": "Слово.",
    "God,": "Бог,",
    "God.": "Бог.",
    "Him": "Его",
    "Him.": "Его.",
    "Him,": "Его,",
    "him.": "его.",
    "him,": "его,",
    "them.": "их.",
    "them,": "их,",
    "you.": "тебя.",
    "you,": "тебя,",
    "me.": "меня.",
    "me,": "меня,",
    "it.": "это.",
    "it,": "это,",
    "at": "у",
    "At": "У",
    "without": "без",
    "Without": "Без",
    "place": "место",
    "places": "места",
    "person": "лицо",
    "persons": "лица",
    "anyone": "кто-либо",
    "everyone": "каждый",
    "someone": "кто-то",
    "something": "нечто",
    "nothing": "ничто",
    "everything": "всё",
    "descendants": "потомки",
    "utterance": "изречение",
    "please": "прошу",
    "Please": "Прошу",
    "may": "да",
    "May": "Да",
    "shall": "будет",
    "will": "будет",
    "would": "бы",
    "could": "мог",
    "should": "должен",
    "must": "должен",
    "can": "может",
    "might": "мог бы",
    "concerning": "о",
    "according": "по",
    "except": "кроме",
    "instead": "вместо",
    "during": "во время",
    "beyond": "за",
    "toward": "к",
    "towards": "к",
    "just": "как",
    "just,": "как,",
    "having": "имея",
    "Having": "Имея",
    "saying;": "говоря;",
    "saying,": "говоря,",
    "saying:": "говоря:",
    "hundred<s>": "сотни",
    "hundreds": "сотни",
    "exceedingly": "чрезвычайно",
    "perpetuity": "вечность",
    "certainly": "непременно",
    "surely": "воистину",
    "humankind": "человечество",
    "hosts": "воинств",
    "kings": "цари",
    "peoples": "народы",
    "work": "дело",
    "works": "дела",
    "working": "работая",
    "wife": "жена",
    "wives": "жёны",
    "husband": "муж",
    "some": "некоторые",
    "any": "любой",
    "lest": "чтобы не",
    "ark": "ковчег",
    "tent": "шатёр",
    "tents": "шатры",
    "tabernacle": "скиния",
    "food": "пища",
    "second": "второй",
    "third": "третий",
    "fourth": "четвёртый",
    "fifth": "пятый",
    "sixth": "шестой",
    "seventh": "седьмой",
    "tribe": "колено",
    "tribes": "колена",
    "chief": "начальник",
    "chiefs": "начальники",
    "camp": "стан",
    "camps": "станы",
    "sound": "звук",
    "sounds": "звуки",
    "scroll": "свиток",
    "living": "живущий",
    "alive": "живой",
    "congregation": "собрание",
    "assembly": "собрание",
    "entrance": "вход",
    "ground": "земля",
    "dust": "прах",
    "sun": "солнце",
    "moon": "луна",
    "star": "звезда",
    "stars": "звёзды",
    "cloud": "облако",
    "clouds": "облака",
    "rain": "дождь",
    "wind": "ветер",
    "matter": "дело",
    "meeting": "собрание",
    "mine": "мой",
    "Mine": "Мой",
    "myself": "себя",
    "yourself": "себя",
    "yourselves": "себя",
    "ourselves": "себя",
    "burnt": "всесожжение",
    "inhabitants": "жители",
    "elders": "старейшины",
    "gods": "боги",
    "God's": "Божий",
    "unto": "к",
    "forth": "вперёд",
    "thereof": "того",
    "thereof,": "того,",
    "wherein": "в чём",
    "wherefore": "потому",
    "Wherefore": "Потому",
    "whence": "откуда",
    "thence": "оттуда",
    "hither": "сюда",
    "thither": "туда",
    "hence": "отсюда",
    "abroad": "вдали",
    "within": "внутри",
    "outside": "снаружи",
    "inside": "внутри",
    "open": "открыть",
    "opened": "открыл",
    "close": "закрыть",
    "closed": "закрыл",
    "keep": "хранить",
    "kept": "хранил",
    "fill": "наполнить",
    "filled": "наполнил",
    "full": "полный",
    "empty": "пустой",
    "destroy": "уничтожить",
    "destroyed": "уничтожен",
    "destruction": "разрушение",
    "build": "строить",
    "built": "построил",
    "break": "разбить",
    "broke": "разбил",
    "broken": "сломанный",
    "gather": "собирать",
    "gathered": "собрал",
    "scatter": "рассеять",
    "scattered": "рассеянный",
    "write": "писать",
    "wrote": "написал",
    "written": "написанное",
    "read": "читать",
    "teach": "учить",
    "taught": "учил",
    "learn": "учиться",
    "learned": "научился",
    "walk": "ходить",
    "walked": "ходил",
    "walking": "ходящий",
    "run": "бежать",
    "ran": "побежал",
    "carry": "нести",
    "carried": "нёс",
    "lift": "поднять",
    "lifted": "поднял",
    "hold": "держать",
    "held": "держал",
    "possess": "владеть",
    "possessed": "владел",
    "possession": "владение",
    "inherit": "наследовать",
    "inheritance": "наследие",
    "receive": "принять",
    "received": "принял",
    "accept": "принять",
    "offer": "приносить",
    "offered": "принёс",
    "serve": "служить",
    "served": "служил",
    "service": "служение",
    "worship": "поклоняться",
    "worshiped": "поклонялся",
    "bow down": "поклониться",
    "obey": "повиноваться",
    "obeyed": "повиновался",
    "follow": "следовать",
    "followed": "последовал",
    "answer": "ответ",
    "answered": "ответил",
    "ask": "спросить",
    "asked": "спросил",
    "seek": "искать",
    "sought": "искал",
    "find": "найти",
    "found": "нашёл",
    "hide": "скрыть",
    "hidden": "скрытый",
    "show": "показать",
    "showed": "показал",
    "shown": "показанный",
    "reign": "царствовать",
    "reigned": "царствовал",
    "rule": "править",
    "ruled": "правил",
    "ruler": "правитель",
    "free": "свободный",
    "freedom": "свобода",
    "captive": "пленник",
    "captivity": "плен",
    "enemy": "враг",
    "enemies": "враги",
    "friend": "друг",
    "friends": "друзья",
    "neighbor": "ближний",
    "stranger": "чужеземец",
    "foreigner": "иноземец",
    "rich": "богатый",
    "poor": "бедный",
    "wealth": "богатство",
    "poor,": "бедный,",
    "treasure": "сокровище",
    "long": "долгий",
    "short": "короткий",
    "high": "высокий",
    "low": "низкий",
    "deep": "глубокий",
    "wide": "широкий",
    "narrow": "узкий",
    "white": "белый",
    "black": "чёрный",
    "red": "красный",
    "green": "зелёный",
    "whole": "весь",
    "half": "половина",
    "part": "часть",
    "parts": "части",
    "end.": "конец.",
    "end,": "конец,",
    "forever.": "вовек.",
    "forever,": "вовек,",
    "number": "число",
    "count": "считать",
    "measure": "мера",
    "weight": "вес",
    "border": "граница",
    "boundary": "граница",
    "corner": "угол",
    "side": "сторона",
    "sides": "стороны",
    "north": "север",
    "south": "юг",
    "east": "восток",
    "west": "запад",
    "right hand": "правая рука",
    "left hand": "левая рука",
    "Moab": "Моав",
    "Ammon": "Аммон",
    "Edom": "Едом",
    "Syria": "Сирия",
    "Assyria": "Ассирия",
    "Persia": "Персия",
    "Tyre": "Тир",
    "Sidon": "Сидон",
    "Gilead": "Галаад",
    "Lebanon": "Ливан",
    "Bethlehem": "Вифлеем",
    "Nazareth": "Назарет",
    "Capernaum": "Капернаум",
    "Jews": "Иудеи",
    "Jew": "Иудей",
    "Jewish": "Иудейский",
    "Levites": "Левиты",
    "Pharisees": "Фарисеи",
    "Sadducees": "Саддукеи",
    "scribes": "книжники",
    "Gentiles": "язычники",
    "Gentile": "язычник",
    "Joab": "Иоав",
    "Aram": "Арам",
    "Rehoboam": "Ровоам",
    "Jeroboam": "Иеровоам",
    "Andrew": "Андрей",
    "Philip": "Филипп",
    "Thomas": "Фома",
    "James": "Иаков",
    "Barnabas": "Варнава",
    "Timothy": "Тимофей",
    "Pilate": "Пилат",
    "Herod": "Ирод",
    "there!": "вот!",
    "here!": "вот!",
    "O": "О",
    "teen": "надцать",
    "maybe": "может быть",
    "cubits": "локтей",
    "cubit": "локоть",
    "year.": "год.",
    "year,": "год,",
    "Jesus;": "Иисус;",
    "Jesus,": "Иисус,",
    "Jesus.": "Иисус.",
    "Lord,": "Господь,",
    "Lord.": "Господь.",
    "Israel.": "Израиль.",
    "Israel,": "Израиль,",
    "Christ.": "Христос.",
    "Christ,": "Христос,",
    "David.": "Давид.",
    "David,": "Давид,",
    "Jerusalem.": "Иерусалим.",
    "Jerusalem,": "Иерусалим,",
    "Egypt.": "Египет.",
    "Egypt,": "Египет,",
    "(s)he called": "назвал",
    "и, there!": "и, вот!",
    "и, оно will быть": "и будет",
    "оно will быть": "будет",
    "О Яхве": "О Яхве",
    "О, Яхве": "О Яхве",
    "herself": "себя",
    "при, в": "при",
    "what?": "что?",
    "who?": "кто?",
    "there-": "по-",
    "-fore": "тому",
    # More common words
    "around": "вокруг",
    "anything": "что-либо",
    "firstborn": "первенец",
    "throne": "престол",
    "bronze": "медь",
    "army": "войско",
    "wicked": "нечестивый",
    "fathers": "отцы",
    "wall": "стена",
    "walls": "стены",
    "account": "счёт",
    "immediately": "тотчас",
    "ancestors": "предки",
    "testimony": "свидетельство",
    "hour": "час",
    "crowd": "толпа",
    "justice": "справедливость",
    "certain": "некий",
    "falsehood": "ложь",
    "Canaan": "Ханаан",
    "clan": "род",
    "clans": "роды",
    "wickedness": "нечестие",
    "commanded": "повелел",
    "belong": "принадлежать",
    "fathered": "родил",
    "arose": "встал",
    "out": "вне",
    "midst": "среда",
    "plus": "плюс",
    "forever": "вовек",
    "ever": "когда-либо",
    "Yours": "Твоё",
    "shines": "светит",
    "grasped": "объяла",
    "has": "имеет",
    "had": "имел",
    "have": "имеют",
    "Has": "Имеет",
    "Have": "Имеют",
    "witness": "свидетель",
    "witnesses": "свидетели",
    "testify": "свидетельствовать",
    "testified": "засвидетельствовал",
    "world.": "мир.",
    "world,": "мир,",
    "Light,": "Свет,",
    "Light.": "Свет.",
    "river.": "река.",
    "river,": "река,",
    "son.": "сын.",
    "son,": "сын,",
    "become": "стать",
    "became": "стал",
    "born": "рождённый",
    "Born": "Рождённый",
    "blood,": "кровь,",
    "blood.": "кровь.",
    "grace,": "благодать,",
    "grace.": "благодать.",
    "dwelt": "обитал",
    "glory,": "слава,",
    "glory.": "слава.",
    "sent.": "послал.",
    "sent,": "послал,",
    "seen.": "видел.",
    "seen,": "видел,",
    "neither": "ни",
    "other": "другой",
    "others": "другие",
    "worthy": "достойный",
    "sandal": "сандалия",
    "strap": "ремень",
    "above": "свыше",
    "Below": "Снизу",
    "baptize": "крестить",
    "baptized": "крестил",
    "baptism": "крещение",
    "dove": "голубь",
    "upon": "на",
    "remained": "оставался",
    "remain": "оставаться",
    "Rabbi": "Равви",
    "master": "учитель",
    "Teacher": "Учитель",
    "where?": "где?",
    "Where?": "Где?",
    "truly": "истинно",
    "Truly,": "Истинно,",
    "heaven.": "небо.",
    "heaven,": "небо,",
    "ascending": "восходящий",
    "descending": "нисходящий",
    "wedding": "свадьба",
    "water,": "вода,",
    "water.": "вода.",
    "sign.": "знамение.",
    "sign,": "знамение,",
    "signs": "знамения",
    "glory": "слава",
    "already": "уже",
    "believe,": "верить,",
    "believe.": "верить.",
    "night": "ночь",
    "night,": "ночь,",
    "night.": "ночь.",
    "again": "снова",
    "eternal": "вечный",
    "Eternal": "Вечный",
    "perish": "погибнуть",
    "condemn": "осудить",
    "condemned": "осуждённый",
    "above,": "свыше,",
    "least": "наименьший",
    "greater": "больший",
    "greatest": "величайший",
    "less": "меньший",
    "larger": "больший",
    "smaller": "меньший",
    "new": "новый",
    "New": "Новый",
    "old": "старый",
    "Old": "Старый",
    "coming,": "приходящий,",
    "coming.": "приходящий.",
    "gave": "дал",
    "given": "данный",
    "each": "каждый",
    "harvest": "жатва",
    "sow": "сеять",
    "sowed": "сеял",
    "reap": "жать",
    "reaped": "жал",
    "well": "колодец",
    "hour.": "час.",
    "hour,": "час,",
    "sick": "больной",
    "heal": "исцелить",
    "healed": "исцелён",
    "healing": "исцеление",
    "whole": "целый",
    "lame": "хромой",
    "blind": "слепой",
    "deaf": "глухой",
    "mute": "немой",
    "leprosy": "проказа",
    "leper": "прокажённый",
    "demon": "бес",
    "demons": "бесы",
    "unclean spirit": "нечистый дух",
    "authority": "власть",
    "Authority": "Власть",
    "parable": "притча",
    "parables": "притчи",
    "loaves": "хлебы",
    "loaf": "хлеб",
    "walk on": "ходить по",
    "storm": "буря",
    "boat": "лодка",
    "net": "сеть",
    "nets": "сети",
    "image": "образ",
    "likeness": "подобие",
    "form": "форма",
    "appeared": "явился",
    "appear": "явиться",
    "revealed": "открыл",
    "reveal": "открыть",
    "revelation": "откровение",
    "Revelation": "Откровение",
    "mystery": "тайна",
    "together": "вместе",
    "raised": "воскрешённый",
    "resurrection": "воскресение",
    "Resurrection": "Воскресение",
    "tomb": "гроб",
    "buried": "погребён",
    "stone.": "камень.",
    "stone,": "камень,",
    "immediately,": "тотчас,",
    "cried out": "воззвал",
    "cry out": "воззвать",
    "shouted": "закричал",
    "whispered": "шептал",
    "touched": "коснулся",
    "touch": "коснуться",
    "stretched out": "простёр",
    "stretch out": "простереть",
    "enough": "достаточно",
    "Enough": "Достаточно",
    "outside": "снаружи",
    "Outside": "Снаружи",
    "clothed": "облечённый",
    "clothing": "одежда",
    "purple": "багряница",
    "scarlet": "червлёный",
    "linen": "виссон",
    "wine,": "вино,",
    "wine.": "вино.",
    "cup": "чаша",
    "table": "стол",
    "eat,": "есть,",
    "eat.": "есть.",
    "Passover": "Пасха",
    "feast": "праздник",
    "feasts": "праздники",
    "sabbath": "суббота",
    "Sabbath": "Суббота",
    "circumcision": "обрезание",
    "circumcised": "обрезан",
    "phylacteries": "филактерии",
    "tithe": "десятина",
    "tithes": "десятины",
    "reward": "награда",
    "rewards": "награды",
    "wages": "плата",
    "tax": "налог",
    "taxes": "налоги",
    "talent": "талант",
    "talents": "таланты",
    "denarius": "динарий",
    "coin": "монета",
    "coins": "монеты",
    "treasure,": "сокровище,",
    "treasure.": "сокровище.",
    "fig tree": "смоковница",
    "mustard seed": "горчичное зерно",
    "leaven": "закваска",
    "salt": "соль",
    "lamp": "светильник",
    "lamps": "светильники",
    "door.": "дверь.",
    "door,": "дверь,",
    "key": "ключ",
    "keys": "ключи",
    "hand.": "рука.",
    "hand,": "рука,",
    "foot.": "нога.",
    "foot,": "нога,",
    "head.": "голова.",
    "head,": "голова,",
    "heart.": "сердце.",
    "heart,": "сердце,",
}

# Handle punctuation: strip trailing punctuation, translate, re-add
PUNCT_RE = re.compile(r'^(.*?)([.,;:!?]+)$')

# Compound gloss translation
def translate_gloss(gloss: str) -> str:
    if not gloss or gloss.strip() == '':
        return ''

    # Direct match
    if gloss in EN_TO_RU:
        return EN_TO_RU[gloss]

    # Handle compound glosses with "/ " separator (STEPBible uses this)
    if '/ ' in gloss:
        parts = gloss.split('/ ')
        translated = []
        for p in parts:
            p = p.strip()
            if p in EN_TO_RU:
                translated.append(EN_TO_RU[p])
            else:
                translated.append(translate_single(p))
        result = ', '.join(t for t in translated if t)
        return result if result else gloss

    return translate_single(gloss)


def translate_single(g: str) -> str:
    if g in EN_TO_RU:
        return EN_TO_RU[g]
    
    # Try with trailing punctuation stripped
    m = PUNCT_RE.match(g)
    if m:
        core, punct = m.group(1), m.group(2)
        if core in EN_TO_RU:
            return EN_TO_RU[core] + punct
        core_lower = core.lower()
        if core_lower in EN_TO_RU:
            result = EN_TO_RU[core_lower]
            if core and core[0].isupper() and result:
                result = result[0].upper() + result[1:]
            return result + punct
    
    # Strip angle brackets <word>
    stripped = re.sub(r'[<>]', '', g).strip()
    if stripped in EN_TO_RU:
        return EN_TO_RU[stripped]
    
    # Try lowercase
    if g and g.lower() in EN_TO_RU:
        result = EN_TO_RU[g.lower()]
        if g[0].isupper() and result:
            return result[0].upper() + result[1:]
        return result
    
    # Try translating word by word for short phrases
    words = g.split()
    if 1 < len(words) <= 5:
        translated_words = []
        any_translated = False
        for w in words:
            clean = re.sub(r'[<>]', '', w).strip()
            pm = PUNCT_RE.match(clean)
            core_w = pm.group(1) if pm else clean
            punct_w = pm.group(2) if pm else ''
            
            if core_w in EN_TO_RU:
                r = EN_TO_RU[core_w]
                if r:
                    translated_words.append(r + punct_w)
                any_translated = True
            elif core_w.lower() in EN_TO_RU:
                r = EN_TO_RU[core_w.lower()]
                if core_w and core_w[0].isupper() and r:
                    r = r[0].upper() + r[1:]
                if r:
                    translated_words.append(r + punct_w)
                any_translated = True
            else:
                translated_words.append(clean)
        if any_translated:
            return ' '.join(translated_words)
    
    return g


def main():
    base = os.path.join(os.path.dirname(__file__), '..', 
                        'app', 'src', 'main', 'assets', 'bible', 'PODSTR')
    files = sorted(glob.glob(os.path.join(base, '*.json')))
    
    total_words = 0
    translated_words = 0
    
    for fp in files:
        with open(fp) as f:
            data = json.load(f)
        
        modified = False
        for ch in data['book']['chapters']:
            for v in ch['verses']:
                for w in v.get('words', []):
                    original_r = w['r']
                    new_r = translate_gloss(original_r)
                    total_words += 1
                    if new_r != original_r:
                        w['r'] = new_r
                        translated_words += 1
                        modified = True
        
        if modified:
            with open(fp, 'w', encoding='utf-8') as f:
                json.dump(data, f, ensure_ascii=False, indent=None, separators=(',', ':'))
        
        bname = os.path.basename(fp)
        print(f"  {bname}: processed")
    
    print(f"\nDone: {translated_words}/{total_words} words translated "
          f"({100*translated_words/total_words:.1f}%)")


if __name__ == '__main__':
    main()
